language: java

jdk:
  - oraclejdk7
  - openjdk6

notifications:
  email:
    recipients:
      - jeff.yemin@10gen.com
      - trisha.gee@10gen.com
    on_success: change 
    on_failure: always 

services:
  - mongodb

branches:
  only:
    - master
