---
differenceTypes:
- 5001 # Removed class from the list of superclasses

classes:
- com.mongodb.util.MyAsserts
- com.mongodb.util.MyAsserts$MyAssert

members:
 com.mongodb.DBPortPool:
  - getStatistics()
  - memSize(com.mongodb.DBPort)
